### ISSUE TITLE
Install problems: libxfoil.so not found

### ISSUE THREAD

**Issue by agaier** [montagdude/libxfoil#3]
Running the given build script (build_libxfoil.sh) everything works fine on my mac. When I try on a remote redhat linux machine it does not find the file:

```
Traceback (most recent call last):
  File "python_example1.py", line 4, in <module>
    import libxfoil_wrap as xiw
  File "/home/agaier2m/.local/lib/python3.7/site-packages/libxfoil_wrap.py", line 27, in <module>
    import libxfoil as xi
  File "/home/agaier2m/.local/lib/python3.7/site-packages/libxfoil.py", line 26, in <module>
    _libxfoil = swig_import_helper()
  File "/home/agaier2m/.local/lib/python3.7/site-packages/libxfoil.py", line 22, in swig_import_helper
    _mod = imp.load_module('_libxfoil', fp, pathname, description)
  File "/home/agaier2m/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/agaier2m/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libxfoil.so: cannot open shared object file: No such file or directory
```

Though libxfoil.so is in install/libxfoil.so

Sorry if I'm missing something obvious!

**Comment by montagdude** [comment]
To be clear, is this happening when you run the build script, or when you attempt to run the python example?

**Comment by agaier** [comment]
When I attempt to run the python example

**Comment by agaier** [comment]
i am on a different mac now. install with new scripts 'seems' to work well (no errors, log messages that look good, etc.) but when I run the python example it gives a strange error, also  seemingly not finding the library:
```

Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import libxfoil.py
Traceback (most recent call last):
  File "/Users/adam/a/Code/libxfoil/python/libxfoil.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/Users/adam/a/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/Users/adam/a/anaconda3/lib/python3.6/site-packages/_libxfoil.cpython-36m-darwin.so, 2): Library not loaded: libxfoil.dylib
  Referenced from: /Users/adam/a/anaconda3/lib/python3.6/site-packages/_libxfoil.cpython-36m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adam/a/Code/libxfoil/python/libxfoil.py", line 17, in <module>
    _libxfoil = swig_import_helper()
  File "/Users/adam/a/Code/libxfoil/python/libxfoil.py", line 16, in swig_import_helper
    return importlib.import_module('_libxfoil')
  File "/Users/adam/a/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Users/adam/a/anaconda3/lib/python3.6/site-packages/_libxfoil.cpython-36m-darwin.so, 2): Library not loaded: libxfoil.dylib
  Referenced from: /Users/adam/a/anaconda3/lib/python3.6/site-packages/_libxfoil.cpython-36m-darwin.so
  Reason: image not found
```

**Comment by montagdude** [comment]
Okay, so I don't know much about Mac, but at least on Linux the reason why it is not found is because build_libxfoil.sh is set up to install in a local directory by default, and when you go to run the example, it doesn't know to look there for the shared library. You can fix that either by installing in a system path like /usr, or use the environment variable LD_LIBRARY_PATH at to tell it where to look at runtime. If you are using bash:

`export LD_LIBRARY_PATH=/path/to/install/lib64`

And then run the Python examples. This will set the environment variable for your session (shell) so that you don't need to enter it again. You can also set the environment variable just for the script but not your shell like this:

`LD_LIBRARY_PATH=/path/to/install/lib64 ./python_example1.py`

**Comment by agaier** [comment]
Perfect! Thanks so much, it works on mac and linux. For others looking at this later, **for mac** the same instructions should be followed but rather than putting

`export LD_LIBRARY_PATH=/path/to/install/lib64`
in your ~/.bashrc

put
`export DYLD_LIBRARY_PATH=/path/to/install/lib64`
in your ~/.bash_profile

**Comment by montagdude** [comment]
Just as a note, in general it's not recommended to set LD_LIBRARY_PATH in your shell startup scripts, because it can cause incompatibilities if you happen to have a different version of a system library installed there. In this case it shouldn't matter, as libxfoil won't interfere with anything, but in general it's better to just set that variable as needed.
